name: magiwatch
description: "A new Flutter project."
publish_to: "none"
version: 1.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  build_runner: ^2.4.9
  dio: ^5.4.2+1
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_wear_os_connectivity: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.2
  rotary_scrollbar: ^0.1.1
  wearable_rotary: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
