name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - main
    
# on: push    # Default will running for every branch.
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - working-directory: ./watch
      run: flutter pub get
    # Check for any formatting issues in the code.
    - working-directory: ./watch
      run: flutter format --set-exit-if-changed .
    # Statically analyze the Dart code for any errors.
    - working-directory: ./watch
      run: flutter analyze . 
    # Run widget tests for our flutter project.
    - working-directory: ./watch
      run: flutter test
    # Build apk.
    - working-directory: ./watch
      run: flutter build apk

    - uses: actions/upload-artifact@v1
      with:
        name: watch-apk
        path: watch/build/app/outputs/apk/release/app-release.apk

    # Get flutter dependencies.
    - working-directory: ./phone
      run: flutter pub get
    # Check for any formatting issues in the code.
    - working-directory: ./phone
      run: flutter format --set-exit-if-changed .
    # Statically analyze the Dart code for any errors.
    - working-directory: ./phone
      run: flutter analyze . 
    # Run widget tests for our flutter project.
    - working-directory: ./phone
      run: flutter test
    # Build apk.
    - working-directory: ./phone
      run: flutter build apk

    - uses: actions/upload-artifact@v1
      with:
        name: phone-apk
        path: phone/build/app/outputs/apk/release/app-release.apk
